### PR TITLE
Update use.md

### PR DESCRIPTION
**Pull request by tarampampam**
## Docker image with CLI open-rpc validator

Validate an OpenRPC json document using docker

Repo: https://github.com/512k/openrpc-validator-docker

### CODE REVIEW

**Comment by shanejonas** [comment]
hey looks great, commit message needs to follow [conventional commits](https://github.com/open-rpc/open-rpc/blob/master/CONVENTIONAL_COMMITS.md)

which just means change your commit message and PR title to be something like:

`fix(use): add  docker image openrpc validator`

**Review by shanejonas — APPROVED** [review]

**Comment by tarampampam** [comment]
@shanejonas fork was deleted, so, now i cannot change commit message. but on merging commit message can be changed on correct

**Review by meowsbits — APPROVED** [review]

**Comment by BelfordZ** [comment]
sorry, cant be merged with out a proper commit message. please re open.

**Comment by tarampampam** [comment]
@BelfordZ too hard for you?

image

**Comment by BelfordZ** [comment]
well, @tarampampam, I must apologize. I thought we had setup a proper contributing.md document, and sufficient instructions, but I was wrong. I've opened an issue to resolve this. 

https://github.com/open-rpc/open-rpc/issues/257

**Comment by BelfordZ** [comment]
@tarampampam https://github.com/open-rpc/open-rpc/pull/258 took 3 minutes. 

Yes, its too hard for me to squash and merge.

**Comment by BelfordZ** [comment]
image

**Comment by tarampampam** [comment]
I understood you. #259

**Pull request closed without merging**
